export const THEME_CHANGE = 'THEME_CHANGE'
//
export const GET_DATA = 'GET_DATA'
export const ERROR_GET = ' ERROR_GET'
export const DATA_FETCHED = 'DATA_FETCHED'
export const SORTED = 'SORTED'
//
export const GET_NEWS = 'GET_NEWS'
export const ERROR_GET_NEWS = 'ERROR_GET_NEWS'
export const LOADING_FETCH = 'LOADING_FETCH'
export const GET_LATEST = 'GET_LATEST'
//
export const LOADING_CHART = 'LOADING_CHART'
export const CHART_READY = 'CHART_READY'
export const ERROR_GET_CHART = 'ERROR_GET_CHART'
//
export const GET_WALLETS = 'GET_WALLETS'
export const ERROR_GET_WALLETS = 'ERROR_GET_WALLETS'
export const LOADING_WALLETS = 'LOADING_WALLETS'
//export const GET_LATEST = "GET_LATEST"
export const LOADING_EXPLORER = 'LOADING_EXPLORER'
export const GET_EXPLORER = 'GET_EXPLORER'
export const ERROR_GET_EXPLORER = 'ERROR_GET_EXPLORER'
//
export const LOADING_COINCHANGE = 'LOADING_COINCHANGE'
export const COINCHANGE_READY = 'COINCHANGE_READY'
export const ERROR_GET_COINCHANGE = 'ERROR_GET_COINCHANGE'
//

// WebSockets
export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
export const WEBSOCKET_CONNECTING = "WEBSOCKET_CONNECTING";
export const WEBSOCKET_CONNECTED = "WEBSOCKET_CONNECTED";
export const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
export const WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED";
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
//
